id: 4
name: 'Adriano Henrique Rossette Leite'
hierarchy_level: 3
login_name: 'adrianohrl'
password: 'teste123'
location: {x: 0.1, y: 0.5, theta: deg(90.0)}
computer: {id: 1, hostname: 'adrianohrl_pc', mobile: false, location: {x: 0.1, y: 0.5, theta: deg(90.0)}}
