id: 5
name: 'Christiano Henrique Rezende'
hierarchy_level: 6
login_name: 'christiano'
password: 'teste1234'
location: {x: 0.3, y: -0.7, theta: deg(90.0)}
computer: {id: 2, hostname: 'christiano_pc', mobile: false, location: {x: 0.3, y: -0.7, theta: deg(90.0)}}
