hostname: 'robotino1'
mobile: true
holonomic: true
location: {x: 10.0, y: 5.0, theta: deg(0.0)}
skill1: {resource: {name: 'velocity', description: 'robot velocity'}, level: 'moderate'} 
skill2: {resource: {name: 'strength', description: 'robot strength'}, level: 'low'} 
skill3: {resource: {name: 'flexible', description: 'robot has flexible movements'}, level: 'high'} 
skill4: {resource: {name: 'vision', description: 'robot implement computer vision algorithms'}, level: 'resourceful'} 
